services:
  redis:
    image: redis:7-alpine
    ports: [ "6379:6379" ]
    command: redis-server --appendonly yes
    volumes: [ redis_data:/data ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    image: ${DOCKERHUB_USERNAME}/producer:${DOCKER_IMAGE_TAG:-latest}
    ports: [ "5001:5000" ]
    env_file: ../.env
    environment:
      - REDIS_HOST=redis
    depends_on: [ redis ]

  worker:
    image: ${DOCKERHUB_USERNAME}/worker:${DOCKER_IMAGE_TAG:-latest}
    expose: [ "5002" ]
    env_file: ../.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - WORKER_ID=worker-1
      - WORKER_CONCURRENCY=2
      - PORT=5002
      - NODE_ENV=production
      - REPORTS_BUCKET=distributed-job-reports
      - AWS_REGION=ap-southeast-1
    depends_on: [ redis ]
    volumes: [ worker_uploads:/app/uploads ]

  scheduler:
    image: ${DOCKERHUB_USERNAME}/scheduler:${DOCKER_IMAGE_TAG:-latest}
    env_file: ../.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - MODE=scheduler
      - NODE_ENV=production
    depends_on: [ redis ]

  dashboard-api:
    image: ${DOCKERHUB_USERNAME}/dashboard-api:${DOCKER_IMAGE_TAG:-latest}
    ports: [ "5003:5003" ]
    env_file: ../.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - REPORTS_BUCKET_NAME=${REPORTS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION:-ap-southeast-1}
    depends_on: [ redis ]

  dashboard-frontend:
    image: ${DOCKERHUB_USERNAME}/dashboard-ui:${DOCKER_IMAGE_TAG:-latest}
    ports: [ "5004:5004" ]
    environment:
      - FRONTEND_PORT=5004
      - NODE_ENV=production
    depends_on: [ dashboard-api ]

volumes:
  redis_data:
  worker_uploads:
